### PR TITLE
HMOS Zzhorizontalprogressbar lib

### PR DESCRIPTION
**Pull request by vidyaakbar**

### CODE REVIEW

**Review by samuel-abhishek — DISMISSED** [review]
Please check these changes to be made yet : 
1. build.gradle - task checkstyle, the old name is still present.
2. ReadMe - in dependancy section
3. ReadMe - Usage section in xml 
4. Both the string.jsons in the project

**Review by samuel-abhishek — APPROVED** [review]
ok

**Review by sharathks84 — APPROVED** [review]
Okay Approved

**Review by Gleelakrishna — APPROVED** [review]
ok

**Pull request merged**
